### ISSUE TITLE
Minimum EV SOC not working

### ISSUE THREAD

**Issue by woopstar** [jonasbkarlsson/ev_smart_charging#185] opened 2023-07-31 08:23 UTC
I'm  currently running v1.8.0.

I have set Minimum EV SoC to 25%, but when I plug in my car and the SoC is less than 25% it does not start to charge the car.

The Charging sensor keeps begin "Off". The SoC from the car was 15%.

Added screenshots also.

![IMG_9748](https://github.com/jonasbkarlsson/ev_smart_charging/assets/2997782/a62b2489-f098-4213-af23-75727bb0717b)
![IMG_9749](https://github.com/jonasbkarlsson/ev_smart_charging/assets/2997782/8fc0b11a-9601-4b6b-bdc5-b36140099d55)
![IMG_9750](https://github.com/jonasbkarlsson/ev_smart_charging/assets/2997782/1cc376ea-cae3-4833-a935-25476b3041af)

**Comment by jonasbkarlsson** [comment] 2023-07-31 08:57
What you described is the current implementation. Minimum EV SoC is used together with Apply price limit to charge the car to the Minimum EV SoC even if the price is higher than the price limit. Note that this charging still is done at the lowest price, and not directly when connecting the car to the charger.

To start charging directly when connected to the charger has been requested in #168.

**Comment by woopstar** [comment] 2023-07-31 09:15
What is then the difference between Minimum SoC and target SoC?

One would assume that minimum SoC means: Charge to this SoC as soon as the charger is connected whereas
Target SoC is: Charge to this SoC no later than Charge complete time, but at the cheapest possible time.

With the current way, it would charge to Minimum SoC within the Completed time hence as I understand Minimum SoC equals at least Target SoC, unless you set Target SoC lower than Minimum SoC (why would you ever do so)

**Comment by onrust** [comment] 2023-08-20 07:58
It appears to be not working as you described. I'm having similar issue as the OP: Minimum SoC doesn't make the car charge when it's plugged in with a SoC lower than the set minimum, no matter the other settings.

**Comment by jonasbkarlsson** [comment] 2023-08-20 09:24
Sorry if my description wasn't clear. What you observe is the intended behaviour of the current implementation, i.e. `Minimum SoC doesn't make the car charge when it's plugged in with a SoC lower than the set minimum`.

To start charging immediately when connected to the charger, if SOC is lower than some value, has been requested in #168.

Since this is a dublicate, I will close this issue.

**Closed by jonasbkarlsson** 2023-08-20 09:24 UTC
