### ISSUE TITLE
No charging planned when charge completion time is after lates available price hour

### ISSUE THREAD

**Issue by oveand** [jonasbkarlsson/ev_smart_charging#139] opened 2023-02-26 08:32 UTC
I've noted that when charge completion time is before the current time, i.e. tomorrow, then no charging is planned, most likely due to EV Smart Charging not having price information available for tomorrow. This is in general alright, though during this weekend the electricity price in DK1 has been cheapest from 10:00-15:00, even cheaper than during the night.
The consequence is that EV Smart Charging does not plan any charging before prices for tomorrow is available, hence I miss the cheap spot during day hours. If I change charge completion time to 23:00 charging is planned just fine.

I understand the rationale of not planning charging periods until price periods for the entire charging period is available, but this has the mentioned drawback, when the spot prices are only available from 13:00 (in DK). Would it be better to plan charging for the time period where electricity prices are available? Electricity prices could be delayed too, of other services (Energi Data Service, Nord Pool, or other in the chain) fails.

![ev_smart_charging_screendump_2](https://user-images.githubusercontent.com/13885942/221399985-8faced70-7ae3-44b9-8d2c-c2b279204ca9.png)
![ev_smart_charging_settings](https://user-images.githubusercontent.com/13885942/221400078-0ef334c6-7a6c-4eb5-86e4-02c5e4553f86.png)

**Comment by oveand** [comment] 2023-02-26 08:37
Hmm. Was playing a bit around with this yesterday and now today I've just restarted HA due to other configuration changes, and now charging _is_ planned planned for today..
Perhaps this was a local glitch, fixed by a restart? I'll investigate..

**Comment by oveand** [comment] 2023-02-26 08:47
Aha.. I've played even more around with the integration and found some interesting (inconsistent) behaviour

- Setting Completion time to 07:00 (tomorrow) and reload EV Smart Charging integration
  - No charging is planned
- Setting Completion time to 06:00 (tomorrow)
  - No charging planned
- Setting Completion time to None OR later today, e.g., 23:00
  - Charging is planned for today
- Setting Completion time to 07:00 (tomorrow)
  - Charging is planned for today
- Reload EV Smart Charging
  - No charging is planned 
- Setting Completion time to 23:00 or None and reload EV Smart Charging integration
  - Charging is planned for today

**Comment by jonasbkarlsson** [comment] 2023-02-26 11:28
Thanks for all the comments.

Setting the Completion time to None is the intended way to "plan charging for the time period where electricity prices are available". I should update the documentation to make that clearer.

Looking at the list of behaviours above, all of them are the intended behaviour, expect the second "Setting Completion time to 07:00 (tomorrow)". I think that one should result in "No charging is planned". I will look into that.

**Comment by jonasbkarlsson** [comment] 2023-02-26 14:27
This issue should now be fixed by #141  and is included in [v1.7.0](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.7.0).

**Closed by jonasbkarlsson** 2023-02-26 14:27 UTC
