### ISSUE TITLE
Stop (manual) charging if the vehicle cable is disconnected.

### ISSUE THREAD

**Issue by Dominic-070** [jonasbkarlsson/ev_smart_charging#116] opened 2023-01-28 10:48 UTC
Stop (manual) charging if the vehicle cable is disconnected.

Now, if the cable is unplugged, charging will continue until manually stopped again. This can be solved with an automation, but it would be nice if this happens as standard.

**Comment by jonasbkarlsson** [comment] 2023-01-28 11:03
What do you mean by "vehicle cable is broken"? If someone has cut it in two pieces?

If the cable is broken, the car and the carging box should be designed to stop the charging to make sure there there is no electricity hazard for people touching the broken charging cable.

**Comment by Dominic-070** [comment] 2023-01-28 11:11
sorry i mean disconnected

**Comment by jonasbkarlsson** [comment] 2023-01-28 11:42
The integration needs some kind of input in order to understand that the cable is disconnected. The current way to get this information is by the `switch.ev_smart_charging_ev_connected`. This switch can either be controlled by automations or manually. 

I think you are asking for a way for the integration to automatically understand that the cable is disconnected, without the need of automations. Unfortunately, the way to get this information differs between different car integrations and different charging box integrations, and there are no plans for this integration to be able to understand all kinds of cars and charging boxes.

Or did you ask for a manual way to stop the charging? If so, then you can do that with `switch.ev_smart_charging_ev_connected`.

**Comment by Dominic-070** [comment] 2023-01-28 14:33
This morning I had started manual loading.
I unplugged my Tesla. The automation turned off the "vehicle connected" switch as it should.
Only sensor.ev_smart_charging_charging remained on. The result is when you plug the car back in, the car immediately continues charging, not in the cheapest hour.

**Comment by jonasbkarlsson** [comment] 2023-01-28 14:59
Which version of the integratin are you using? v1.6.0 or somthing older?
Can you go to `Settings -> Devices & Services -> Integrations -> EV Smart Charging -> 1 device` and let me know what settings and values you have in "Controls" and in "Settings"? (A sceenshot of those parts would be fine.)
When you say "This morning I had started manual charging", exactly how did you do that? By pressing the "Manually start charging" button in this integration, or in some other way?
What is HEVC?
What time did you unplugg the car? Before or after the setting of `select.ev_smart_charging_charge_completion_time`?

**Comment by Dominic-070** [comment] 2023-01-28 15:11
V1.6.0
Around 9:30 am the battery percentage was about 87%.
Set limit was 90%.
I turned on the HEVC and then pressed the manualy start charing button `button.ev_smart_charging_manually_start_charging`.
I unplugged the cable around 10am. The sensor charging `sensor.ev_smart_charging_charging` remained on after disconnecting the cable.
Time complete is set to 07:00
HEVC = Airco, Preheating / Cooling
![image](https://user-images.githubusercontent.com/62623885/215273749-e8757d4a-e05d-47bf-bd5f-40bb00a398ae.png)

**Comment by jonasbkarlsson** [comment] 2023-01-28 15:41
Thank you for the information. Now I understand the situation.

What you have seen is the intended behaviour with the current implementation of the integration. The `button.ev_smart_charging_manually_start_charging` and `button.ev_smart_charging_manually_stop_charging` are as decribed in the documentation "totally independent of the automatic charging".

The automatic charging part of the integration only turns off the charger if it has been turn on by the automatic charging part and the charging should be turned off. With the current implementation, the automatic charging part of the integration does not know that you have used the manual part of the integration to turn on the charger.

So it would better to add one connection between the manual and automatic part of the integration.
- If switch.ev_smart_charging_ev_connected is set to 'off', then the charging should always be turn off.

I will put this on my to-do-list.

Meanwhile, you can manually turn off the charger by pressing the `button.ev_smart_charging_manually_stop_charging`.

**Comment by jonasbkarlsson** [comment] 2023-01-28 22:43
Fixed by #121. Will be part of next release.

**Closed by jonasbkarlsson** 2023-01-28 22:43 UTC
Labels: feature request

**Comment by Dominic-070** [comment] 2023-01-30 09:16
Thank you very much!!
