### ISSUE TITLE
Make time selection not only hourly, but down to half or quater

### ISSUE THREAD

**Issue by AlexJacu** [jonasbkarlsson/ev_smart_charging#348] opened 2024-12-24 02:11 UTC
I would prefer, if i could select Load until 11:30 but not only 11:00 or 12:00

**Comment by jonasbkarlsson** [comment] 2024-12-24 11:13
This is a duplicate of #269, and also related to #88.

**Closed by jonasbkarlsson** 2024-12-24 11:13 UTC

**Comment by jonasbkarlsson** [comment] 2024-12-24 11:15
I close this as duplicate. The feature is not yet implemented.
